/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface PositionDescriptorInterface extends utils.Interface {
  functions: {
    "getMetadata(address,uint256)": FunctionFragment;
    "positionRenderer()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getMetadata",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "positionRenderer",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "getMetadata",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "positionRenderer",
    data: BytesLike
  ): Result;

  events: {};
}

export interface PositionDescriptor extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: PositionDescriptorInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    getMetadata(
      engine: string,
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    positionRenderer(overrides?: CallOverrides): Promise<[string]>;
  };

  getMetadata(
    engine: string,
    tokenId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  positionRenderer(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    getMetadata(
      engine: string,
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    positionRenderer(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    getMetadata(
      engine: string,
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    positionRenderer(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    getMetadata(
      engine: string,
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    positionRenderer(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
